version: '3.9'

services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shortener
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: '../'
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ../
        target: /app
    ports:
      - '3000:3000'
